/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'

const AuthLoginIndexLazyRouteImport = createFileRoute('/_auth/login/')()
const AuthLoginPhoneNumberOtpLazyRouteImport = createFileRoute(
  '/_auth/login/$phoneNumber/otp',
)()

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginIndexLazyRoute = AuthLoginIndexLazyRouteImport.update({
  id: '/_auth/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/_auth/login/index.lazy').then((d) => d.Route),
)
const AuthLoginPhoneNumberOtpLazyRoute =
  AuthLoginPhoneNumberOtpLazyRouteImport.update({
    id: '/_auth/login/$phoneNumber/otp',
    path: '/login/$phoneNumber/otp',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/_auth/login/$phoneNumber.otp.lazy').then((d) => d.Route),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginIndexLazyRoute
  '/login/$phoneNumber/otp': typeof AuthLoginPhoneNumberOtpLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginIndexLazyRoute
  '/login/$phoneNumber/otp': typeof AuthLoginPhoneNumberOtpLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth/login/': typeof AuthLoginIndexLazyRoute
  '/_auth/login/$phoneNumber/otp': typeof AuthLoginPhoneNumberOtpLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/login/$phoneNumber/otp'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/login/$phoneNumber/otp'
  id: '__root__' | '/' | '/_auth/login/' | '/_auth/login/$phoneNumber/otp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLoginIndexLazyRoute: typeof AuthLoginIndexLazyRoute
  AuthLoginPhoneNumberOtpLazyRoute: typeof AuthLoginPhoneNumberOtpLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login/$phoneNumber/otp': {
      id: '/_auth/login/$phoneNumber/otp'
      path: '/login/$phoneNumber/otp'
      fullPath: '/login/$phoneNumber/otp'
      preLoaderRoute: typeof AuthLoginPhoneNumberOtpLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLoginIndexLazyRoute: AuthLoginIndexLazyRoute,
  AuthLoginPhoneNumberOtpLazyRoute: AuthLoginPhoneNumberOtpLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
